apiVersion: v1
kind: Service
metadata:
  name: simpsons-quotes-api
  labels:
    app: simpsons-quotes
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: tcp-port
  selector:
    app: simpsons-quotes
    tier: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpsons-quotes
  labels:
    app: simpsons-quotes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpsons-quotes
      tier: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simpsons-quotes
        tier: api
    spec:
      containers:
      - image: simpsons-quotes:0.1.3
        name: simpsons-quotes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: simpsons-quotes-mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: root
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always